[project]
name = "python-library-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rob Enderle", email = "robenderleamd@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
python-library-test = "python_library_test:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
